import java.util.*;
import java.util.stream.Collectors;

public class JsTranspiler {
    private final StringBuilder out = new StringBuilder();
    private int indent = 0;
    private int scopeCounter = 1;
    private final List<String> warnings = new ArrayList<>();
    private final Deque<Set<String>> scopes = new ArrayDeque<>();
    private String currentFunction = null;
    private String currentClass = null;
    private final Map<String, Integer> functions = new HashMap<>();
    private final Set<String> classes = new HashSet<>();
    private String currentScope = "__scope0";
    public String transpile(List<Stmt> statements) {
        scopes.push(new HashSet<>());
        out.append("// Generated by Lox→JS Transpiler\n\n");
         // __scope0 = globales Scope-Objekt, keine Parent-Scope → Object.create(null)
        out.append("var __scope0 = Object.create(null);\n"); 
           
        // Pre-declare functions for hoisting
        preDeclareFunctions(statements);
        
        // ÄNDERUNG 1: Runtime-Helfer für Lox-spezifisches Verhalten einfügen
        emitLoxRuntimeHelpers();
        
        for (Stmt stmt : statements) emitStmt(stmt);
        
        if (!warnings.isEmpty()) {
            out.insert(0, "// WARNINGS:\n" + warnings.stream().map(w -> "//  - " + w + "\n").collect(Collectors.joining()) + "\n");
        }
        return out.toString();
    }

    // NEUE METHODE: Nur die Lücken füllen, wo JS anders ist als Lox
    private void emitLoxRuntimeHelpers() {
        out.append("\n// Lox Runtime Compatibility Helpers\n");
        
        // 1. Truthiness (Lox: false und nil sind falsy, alles andere truthy)
        out.append("const loxIsTruthy = (v) => !(v === false || v === null);\n");
        
        // 2. Addition (Lox: nur Zahlen + Zahlen oder Strings + Strings)
        out.append("function loxAdd(a, b) {\n");
        out.append("  if (typeof a === 'number' && typeof b === 'number') return a + b;\n");
        out.append("  if (typeof a === 'string' && typeof b === 'string') return a + b;\n");
        out.append("  throw new Error('Operands must be two numbers or strings.');\n");
        out.append("}\n");
        
        // 3. Equality (Lox: == vergleicht Werte, nicht Typen)
        out.append("function loxEqual(a, b) {\n");
        out.append("  if (a === null && b === null) return true;\n");
        out.append("  if (a === null || b === null) return false;\n");
        out.append("  if (typeof a === 'number' && typeof b === 'number') return a === b;\n");
        out.append("  if (typeof a === 'string' && typeof b === 'string') return a === b;\n");
        out.append("  if (typeof a === 'boolean' && typeof b === 'boolean') return a === b;\n");
        out.append("  return false;\n");
        out.append("}\n");
        
        // 4. Logical Operators (Lox: Kurzschluss, aber gibt Wert zurück, nicht Boolean)
        out.append("function loxOr(a, b) { return loxIsTruthy(a) ? a : b(); }\n");
        out.append("function loxAnd(a, b) { return loxIsTruthy(a) ? b() : a; }\n");
        
        // 5. Print (Lox: print gibt nil zurück und formatiert wie Java)
        out.append("function loxPrint(v) {\n");
        out.append("  if (v === null) console.log('nil');\n");
        out.append("  else console.log(String(v));\n");
        out.append("  return null;\n");
        out.append("}\n\n");
        // 6. Variable Lookup mit Scope-Kette (Lox: Zugriff auf Variablen in äußeren Blöcken)
        out.append("function getVar(scope, name) {\r\n" + //
                        "  if (name in scope) return scope[name];\r\n" + //
                        "  if (scope.__parent__) return getVar(scope.__parent__, name);\r\n" + //
                        "  throw new Error(\"Variable not found: \" + name);\r\n" + //
                        "}\n");
    }

    private void preDeclareFunctions(List<Stmt> statements) {
        for (Stmt stmt : statements) {
            if (stmt instanceof Stmt.Function f) {
                functions.put(f.name().lexem(), f.params().size());
            } else if (stmt instanceof Stmt.Class c) {
                classes.add(c.name().lexem());
                for (Stmt.Function m : c.methods()) {
                    if (m.name().lexem().equals("init")) {
                        functions.put(c.name().lexem() + ".constructor", m.params().size());
                    } else {
                        functions.put(c.name().lexem() + "." + m.name().lexem(), m.params().size());
                    }
                }
            }
        }
    }

    private void emitIndent() { out.append("  ".repeat(indent)); }

    private void emitStmt(Stmt stmt) {
        switch (stmt) {
          case Stmt.Var v -> {
            String name = v.name().lexem();

            if (scopes.peek().contains(name)) 
                warnings.add("Variable '" + name + "' already declared in this block");
            else 
                scopes.peek().add(name);

            emitIndent();
            out.append(currentScope).append(".").append(name);
            if (v.initializer() != null) {
                out.append(" = "); 
                emitExpr(v.initializer());
            } else {
                out.append(" = null");  // explizit null für nicht initialisierte Variablen
            }
            out.append(";\n");
        }
            case Stmt.Print p -> { 
                emitIndent(); 
                // ÄNDERUNG 3: print gibt nil zurück
                out.append("loxPrint("); 
                emitExpr(p.expr()); 
                out.append(");\n"); 
            }
            case Stmt.Expression e -> { 
                emitIndent(); 
                emitExpr(e.expr()); 
                out.append(";\n"); 
            }
            case Stmt.Block b -> {
                emitIndent(); 
                out.append("{\n");
                indent++;
                String parentScope = currentScope;                  // merken, was außen liegt
                currentScope = "__scope" + scopeCounter;           // neues Scope
                 scopeCounter++;
                 emitIndent();
                out.append("let ").append(currentScope)
                .append(" = Object.create(").append(parentScope).append(");\n");
                out.append(currentScope).append(".__parent__ = ").append(parentScope).append(";\n");

                scopes.push(new HashSet<>());
                for (Stmt s : b.statements()) emitStmt(s);
                scopes.pop(); currentScope = parentScope; indent--; emitIndent();
                emitIndent(); out.append("}\n");    
                 
            }
            case Stmt.If i -> {
                emitIndent(); 
                // ÄNDERUNG 4: Lox-Truthiness verwenden
                out.append("if (loxIsTruthy("); 
                emitExpr(i.condition()); 
                out.append(")) ");
                emitStmt(i.thenBranch());
                i.elseBranch().ifPresent(elseBranch -> { 
                    emitIndent(); out.append("else "); 
                    emitStmt(elseBranch); 
                });
            }
            case Stmt.While w -> { 
                emitIndent(); 
                // ÄNDERUNG 5: Lox-Truthiness verwenden
                out.append("while (loxIsTruthy("); 
                emitExpr(w.condition()); 
                out.append(")) "); 
                emitStmt(w.body()); 
            }
            case Stmt.Function f -> {
                String prevFunc = currentFunction; 
                currentFunction = f.name().lexem();
                functions.put(currentFunction, f.params().size());
                scopes.peek().add(currentFunction);
                
                emitIndent(); out.append("function ").append(currentFunction).append("(");
                for (int j=0;j<f.params().size();j++){
                    if(j>0) out.append(", "); 
                    out.append(f.params().get(j).lexem());
                }
                out.append("){\n"); 
                indent++;
                
                scopes.push(new HashSet<>());
                for (var p : f.params()) scopes.peek().add(p.lexem());
                
                for (Stmt s : f.body()) emitStmt(s);
                
                // ÄNDERUNG 6: Implizites return null am Ende
                emitIndent(); out.append("return null;\n");
                
                scopes.pop(); 
                indent--; 
                emitIndent(); 
                out.append("}\n");
                currentFunction = prevFunc;
            }
            case Stmt.Class c -> {
                String prevClass = currentClass; 
                currentClass = c.name().lexem();
                classes.add(currentClass);
                scopes.peek().add(currentClass);
                
                emitIndent(); 
                out.append("class ").append(currentClass);
                if (c.superClass() != null) {
                    out.append(" extends ").append(c.superClass().name().lexem());
                }
                out.append(" {\n"); 
                indent++;

                for (Stmt.Function m : c.methods()) {
                    String prevFunc = currentFunction;
                    currentFunction = m.name().lexem();
                    String methodName = m.name().lexem();
                    boolean isConstructor = false;
                    
                    if (methodName.equals("init")) {
                        methodName = "constructor";
                        isConstructor = true;
                        functions.put(currentClass + ".constructor", m.params().size());
                    } else {
                        functions.put(currentClass + "." + methodName, m.params().size());
                    }
                    
                    emitIndent();
                    out.append(methodName).append("(");
                    for (int j=0;j<m.params().size();j++){
                        if(j>0) out.append(", "); 
                        out.append(m.params().get(j).lexem());
                    }
                    out.append(") {\n");
                    
                    indent++;
                    scopes.push(new HashSet<>());
                    for (var p : m.params()) scopes.peek().add(p.lexem());
                    
                    for (Stmt s : m.body()) {
                        emitStmt(s);
                    }
                    
                    // ÄNDERUNG 7: Konstruktor gibt immer this zurück
                    if (isConstructor) {
                        emitIndent(); out.append("return this;\n");
                    }
                    
                    scopes.pop(); 
                    indent--; 
                    emitIndent(); 
                    out.append("}\n");
                    currentFunction = prevFunc;
                }

                indent--; 
                emitIndent(); 
                out.append("}\n");
                currentClass = prevClass;
            }
            case Stmt.Return r -> {
                if (currentFunction == null) {
                    warnings.add("Return statement outside function");
                }
                
                emitIndent(); 
                out.append("return");
                if (r.value() != null) { 
                    out.append(" "); 
                    emitExpr(r.value()); 
                }
                out.append(";\n");
            }
            default -> throw new IllegalStateException("Unhandled statement: " + stmt);
        }
    }

    private void emitExpr(Expr expr) {
        switch (expr) {
            case Expr.Literal l -> {
                Object v = l.value();
                if (v == null) out.append("null");
                else if (v instanceof String s) {
                    out.append("\"").append(escapeString(s)).append("\"");
                } else if (v instanceof Double d) {
                    if (d == Math.rint(d) && !Double.isInfinite(d)) {
                        out.append(String.format("%.0f", d));
                    } else {
                        out.append(d);
                    }
                } else if (v instanceof Boolean b) {
                    out.append(b);
                } else {
                    out.append(v);
                }
            }
            case Expr.Variable v -> {
                String varName = v.name().lexem();
                if (!scopes.stream().anyMatch(s -> s.contains(varName)) && 
                    !varName.equals("print")) { // print is built-in
                    warnings.add("Using variable '" + varName + "' before declaration");
                }
                emitIndent();
                // Zugriff über getVar über Scope-Kette
                 out.append("getVar(").append(currentScope).append(", \"").append(varName).append("\")");
            }

            case Expr.Assign a -> { 
                out.append(a.name().lexem()).append(" = "); 
                emitExpr(a.value()); 
            }
            case Expr.Binary b -> {
                String op = b.operator().lexem();
                
                // ÄNDERUNG 8: Spezielle Behandlung für Addition und Gleichheit
                if (op.equals("+")) {
                    out.append("loxAdd(");
                    emitExpr(b.left());
                    out.append(", ");
                    emitExpr(b.right());
                    out.append(")");
                } else if (op.equals("==")) {
                    out.append("loxEqual(");
                    emitExpr(b.left());
                    out.append(", ");
                    emitExpr(b.right());
                    out.append(")");
                } else if (op.equals("!=")) {
                    out.append("!loxEqual(");
                    emitExpr(b.left());
                    out.append(", ");
                    emitExpr(b.right());
                    out.append(")");
                } else {
                    // Für andere Operatoren normal JavaScript (verhalten sich gleich)
                    out.append("(");
                    emitExpr(b.left()); 
                    out.append(" ").append(op).append(" "); 
                    emitExpr(b.right());
                    out.append(")");
                }
            }
            case Expr.Grouping g -> { 
                out.append("("); 
                emitExpr(g.expression()); 
                out.append(")"); 
            }
            case Expr.Unary u -> {
                String op = u.operator().lexem();
                if (op.equals("!")) {
                    // ÄNDERUNG 9: Lox-Not mit Truthiness
                    out.append("!loxIsTruthy(");
                    emitExpr(u.right());
                    out.append(")");
                } else if (op.equals("-")) {
                    // Negation verhält sich gleich
                    out.append("-");
                    emitExpr(u.right());
                } else {
                    out.append(op);
                    emitExpr(u.right());
                }
            }
            case Expr.Call c -> {
                // Special case: super.init(...) → super(...)
                if (isSuperConstructorCall(c)) {
                    out.append("super(");
                    for (int i = 0; i < c.arguments().size(); i++) {
                        if (i > 0) out.append(", ");
                        emitExpr(c.arguments().get(i));
                    }
                    out.append(")");
                    return;
                }
                
                boolean isConstructorCall = false;
                if (c.callee() instanceof Expr.Variable varExpr) {
                    String calleeName = varExpr.name().lexem();
                    if (classes.contains(calleeName)) {
                        isConstructorCall = true;
                        out.append("new ");
                    }
                }
                
                emitExpr(c.callee());
                out.append("(");
                for (int i = 0; i < c.arguments().size(); i++) {
                    if (i > 0) out.append(", ");
                    emitExpr(c.arguments().get(i));
                }
                out.append(")");
                
                validateCall(c, isConstructorCall);
            }
            case Expr.Logical l -> {
                String op = l.operator().lexem();
                // ÄNDERUNG 10: Lox-logische Operatoren (geben Wert zurück)
                if (op.equals("or")) {
                    out.append("loxOr(");
                    emitExpr(l.left());
                    out.append(", () => ");
                    emitExpr(l.right());
                    out.append(")");
                } else if (op.equals("and")) {
                    out.append("loxAnd(");
                    emitExpr(l.left());
                    out.append(", () => ");
                    emitExpr(l.right());
                    out.append(")");
                } else {
                    warnings.add("Unknown logical operator: " + op);
                    out.append("(");
                    emitExpr(l.left()); 
                    out.append(" || "); 
                    emitExpr(l.right());
                    out.append(")");
                }
            }
            case Expr.This t -> { 
                if (currentClass == null) {
                    warnings.add("'this' used outside class");
                }
                out.append("this"); 
            }
            case Expr.Super s -> { 
                if (currentClass == null) {
                    warnings.add("'super' used outside class");
                }
                out.append("super"); 
            }
            case Expr.Get g -> { 
                emitExpr(g.object()); 
                out.append(".").append(g.name().lexem()); 
            }
            case Expr.Set s -> { 
                emitExpr(s.object()); 
                out.append(".").append(s.name().lexem()).append(" = "); 
                emitExpr(s.value()); 
            }
            default -> throw new IllegalStateException("Unhandled expression: " + expr);
        }
    }

    private boolean isSuperConstructorCall(Expr.Call c) {
        if (!(c.callee() instanceof Expr.Get getExpr)) return false;
        if (!(getExpr.object() instanceof Expr.Super)) return false;
        return getExpr.name().lexem().equals("init");
    }

    private void validateCall(Expr.Call c, boolean isConstructorCall) {
        if (c.callee() instanceof Expr.Variable varExpr) {
            String callee = varExpr.name().lexem();
            
            if (callee.equals("print")) return;
            
            if (isConstructorCall) {
                if (functions.containsKey(callee + ".constructor") && 
                    c.arguments().size() != functions.get(callee + ".constructor")) {
                    warnings.add("Constructor '" + callee + "' expects " + 
                                functions.get(callee + ".constructor") + " args, got " + 
                                c.arguments().size());
                }
            } else {
                if (functions.containsKey(callee) && 
                    c.arguments().size() != functions.get(callee)) {
                    warnings.add("Function '" + callee + "' expects " + 
                                functions.get(callee) + " args, got " + 
                                c.arguments().size());
                }
                
                if (!functions.containsKey(callee) && !classes.contains(callee)) {
                    warnings.add("Call to undefined function '" + callee + "'");
                }
            }
        }
    }

    private String escapeString(String value) {
        return value
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\n", "\\n")
            .replace("\r", "\\r")
            .replace("\t", "\\t");
    }

    public static String transpile(String source) {
        try {
            JsTranspiler t = new JsTranspiler();
            List<Stmt> statements = ParserMain.parseProgram(source);
            return t.transpile(statements);
        } catch(Exception e) { 
            return "// Transpilation failed: " + e.getMessage() + "\n";
        }
    }
}