import java.util.*;
import java.util.stream.Collectors;

public class JsTranspiler {
    private final StringBuilder out = new StringBuilder();
    private int indent = 0;

    private final List<String> warnings = new ArrayList<>();
    private final Deque<Set<String>> scopes = new ArrayDeque<>();
    private String currentFunction = null;
    private String currentClass = null;
    private final Map<String, Integer> functions = new HashMap<>();
    private final Set<String> classes = new HashSet<>();

    public String transpile(List<Stmt> statements) {
        scopes.push(new HashSet<>());
        out.append("// Generated by Lox→JS Transpiler\n\n");
        for (Stmt stmt : statements) emitStmt(stmt);
        if (!warnings.isEmpty()) {
            out.insert(0, "// WARNINGS:\n" + warnings.stream().map(w -> "//  - " + w + "\n").collect(Collectors.joining()) + "\n");
        }
        return out.toString();
    }

    private void emitIndent() { out.append("  ".repeat(indent)); }

    private void emitStmt(Stmt stmt) {
        switch (stmt) {
            case Stmt.Var v -> {
                String name = v.name().lexem();
                if (scopes.peek().contains(name)) warnings.add("Variable '" + name + "' already declared in this block");
                else scopes.peek().add(name);

                emitIndent(); out.append("let ").append(name);
                if (v.initializer() != null) { out.append(" = "); emitExpr(v.initializer()); }
                out.append(";\n");
            }
            case Stmt.Print p -> { emitIndent(); out.append("console.log("); emitExpr(p.expr()); out.append(");\n"); }
            case Stmt.Expression e -> { emitIndent(); emitExpr(e.expr()); out.append(";\n"); }
            case Stmt.Block b -> {
                emitIndent(); out.append("{\n"); indent++;
                scopes.push(new HashSet<>());
                for (Stmt s : b.statements()) emitStmt(s);
                scopes.pop(); indent--; emitIndent(); out.append("}\n");
            }
            case Stmt.If i -> {
                emitIndent(); out.append("if ("); emitExpr(i.condition()); out.append(") ");
                emitStmt(i.thenBranch());
                i.elseBranch().ifPresent(elseBranch -> { emitIndent(); out.append("else "); emitStmt(elseBranch); });
            }
            case Stmt.While w -> { emitIndent(); out.append("while ("); emitExpr(w.condition()); out.append(") "); emitStmt(w.body()); }
            case Stmt.Function f -> {
                String prevFunc = currentFunction; currentFunction = f.name().lexem();
                functions.put(currentFunction, f.params().size());
                emitIndent(); out.append("function ").append(currentFunction).append("(");
                for (int j=0;j<f.params().size();j++){if(j>0) out.append(", "); out.append(f.params().get(j).lexem());}
                out.append("){\n"); indent++;
                scopes.push(new HashSet<>());
                for (var p : f.params()) scopes.peek().add(p.lexem());
                for (Stmt s : f.body()) emitStmt(s);
                scopes.pop(); indent--; emitIndent(); out.append("}\n");
                currentFunction = prevFunc;
            }
            case Stmt.Class c -> {
                String prevClass = currentClass; currentClass = c.name().lexem();
                classes.add(currentClass);
                emitIndent(); out.append("class ").append(currentClass);
                if (c.superClass()!=null) out.append(" extends ").append(c.superClass().name().lexem());
                out.append("{\n"); indent++;
                for (Stmt.Function m : c.methods()) {
                    emitIndent(); out.append(m.name().lexem()).append("(");
                    for (int j=0;j<m.params().size();j++){if(j>0) out.append(", "); out.append(m.params().get(j).lexem());}
                    out.append("){\n"); indent++;
                    scopes.push(new HashSet<>()); scopes.peek().add("this");
                    for (var p : m.params()) scopes.peek().add(p.lexem());
                    for (Stmt s : m.body()) emitStmt(s);
                    scopes.pop(); indent--; emitIndent(); out.append("}\n");
                }
                indent--; emitIndent(); out.append("}\n"); currentClass = prevClass;
            }
            case Stmt.Return r -> {
                if (currentFunction==null) warnings.add("Return statement outside function");
                emitIndent(); out.append("return");
                if (r.value()!=null) { out.append(" "); emitExpr(r.value()); }
                out.append(";\n");
            }
        }
    }

    private void emitExpr(Expr expr) {
        switch (expr) {
            case Expr.Literal l -> {
                Object v = l.value();
                if (v==null) out.append("null");
                else if (v instanceof String s) out.append("\"").append(s.replace("\"","\\\"")).append("\"");
                else out.append(v);
            }
            case Expr.Variable v -> {
                if (!scopes.stream().anyMatch(s -> s.contains(v.name().lexem()))) warnings.add("Using variable '" + v.name().lexem() + "' before declaration");
                out.append(v.name().lexem());
            }
            case Expr.Assign a -> { out.append(a.name().lexem()).append(" = "); emitExpr(a.value()); }
            case Expr.Binary b -> {
                String op = b.operator().lexem();
                if (op.equals("==")) op="==="; if (op.equals("!=")) op="!==";
                emitExpr(b.left()); out.append(" ").append(op).append(" "); emitExpr(b.right());
            }
            case Expr.Grouping g -> { out.append("("); emitExpr(g.expression()); out.append(")"); }
            case Expr.Unary u -> { out.append(u.operator().lexem()); emitExpr(u.right()); }
            case Expr.Call c -> {
                String callee = (c.callee() instanceof Expr.Variable var) ? var.name().lexem() : null;
                emitExpr(c.callee()); out.append("(");
                for (int i=0;i<c.arguments().size();i++){if(i>0) out.append(", "); emitExpr(c.arguments().get(i));}
                out.append(")");
                if (callee!=null) {
                    if (functions.containsKey(callee) && c.arguments().size()!=functions.get(callee))
                        warnings.add("Function '"+callee+"' expects "+functions.get(callee)+" args, got "+c.arguments().size());
                    if (!functions.containsKey(callee) && !classes.contains(callee))
                        warnings.add("Call to undefined function '"+callee+"'");
                }
            }
            case Expr.Logical l -> { emitExpr(l.left()); out.append(" ").append(l.operator().lexem()).append(" "); emitExpr(l.right()); }
            case Expr.This t -> { if (currentClass==null) warnings.add("'this' used outside class"); out.append("this"); }
            case Expr.Super s -> { if (currentClass==null) warnings.add("'super' used outside class"); out.append("super"); }
            case Expr.Get g -> { emitExpr(g.object()); out.append(".").append(g.name().lexem()); }
            case Expr.Set s -> { emitExpr(s.object()); out.append(".").append(s.name().lexem()).append(" = "); emitExpr(s.value()); }
        }
    }

    // =============== ÖFFENTLICHE API ===============
    public static String transpile(String source) {
        try {
            JsTranspiler t = new JsTranspiler();
            List<Stmt> statements = ParserMain.parseProgram(source);
            return t.transpile(statements);
        } catch(Exception e){ return "// Transpilation failed: "+e.getMessage()+"\n"; }
    }

    public static void main(String[] args) { Test(); }

    public static void Test() {
        System.out.println("=== Test 1: Fehlererkennung ===");
        String code1 = """
            var x = 10;
            var x = 20;
            print undefinedVar;
            fun add(a,b){return a+b;}
            add(1,2,3);
            "hello"-5;
            """;
        System.out.println(transpile(code1));

        System.out.println("\n=== Test 2: Korrektes Programm ===");
       String code2 = """
            fun fib(n) {
                if (n <= 1) return n;
                 return fib(n - 1) + fib(n - 2);
                }
            print fib(5);

            class Shape {
                init(color) {
                    this.color = color;
                 }
                describe() {
                print this.color + " shape";
                }
             }

        class Circle < Shape {
            init(color, radius) {
                super.init(color);
                this.radius = radius;
        }
        area() {
            return 3.14 * this.radius * this.radius;
            }
        }

            var  circle = new Circle("red", 5);
                circle.describe();
                print circle.area();
            """;

        System.out.println(transpile(code2));
    }
}
