import java.util.*;


public class JsTranspiler {
    private final StringBuilder out = new StringBuilder();
    private int indent = 0;
    private int scopeCounter = 1;
    private final Deque<Set<String>> scopes = new ArrayDeque<>();
    private final Set<String> classes = new HashSet<>();
    private String currentFunctionScope = null;
    private String currentFunction = null;
    private String currentClass = null;
    private String currentScope = "__scope0";
    public String transpile(List<Stmt> statements) {
        scopes.push(new HashSet<>());
        out.append("// Generated by Lox→JS Transpiler\n\nvar __scope0 = Object.create(null);\n");
        emitLoxRuntimeHelpers();
        for (Stmt stmt : statements) emitStmt(stmt);
        return out.toString();
    }

    

    private void emitIndent() { out.append("  ".repeat(indent)); }
    private void emitCommaSeparated(List<?> items) {

        for (int i = 0; i < items.size(); i++) { 
            if (i > 0) out.append(", ");
            if(items.get(i) instanceof Token t) out.append(t.lexem());
            else if(items.get(i) instanceof Expr e) emitExpr(e);
            else
            out.append(items.get(i));
         }
    }

    private void emitParams(List<Token> params) {
        for (int i = 0; i < params.size(); i++) { if (i > 0) out.append(", "); out.append(params.get(i).lexem()); }
    }

    private void emitNewScopeBlock(Runnable body) {
        String parent = currentScope;
        currentScope = "__scope" + scopeCounter++;
        emitIndent();
        out.append("let ").append(currentScope).append(" = Object.create(").append(parent).append(");\n");
        out.append(currentScope).append(".__parent__ = ").append(parent).append(";\n");
        scopes.push(new HashSet<>());
        body.run();
        scopes.pop();
        currentScope = parent;
    }

    
    private void emitStmt(Stmt stmt) {
        switch (stmt) {
            case Stmt.Var v -> emitVar(v);
            case Stmt.Print p -> emitPrint(p);
            case Stmt.Expression e -> { emitIndent(); emitExpr(e.expr()); out.append(";\n"); }
            case Stmt.Block b -> emitStmtBlock(b.statements());
            case Stmt.If i -> emitIf(i);
            case Stmt.While w -> emitWhile(w);
            case Stmt.Function f -> emitFunction(f, false);
            case Stmt.Class c -> emitClass(c);
            case Stmt.Return r -> emitReturn(r);
            default -> throw new IllegalStateException("Unhandled statement: " + stmt);
        }
    }

    private void emitVar(Stmt.Var v) {
        String name = v.name().lexem();
     
        scopes.peek().add(name);
        emitIndent();
        String scope = (currentFunction != null) ? currentFunctionScope : currentScope;
        out.append(scope).append(".").append(name).append(" = ");
        if (v.initializer() != null) emitExpr(v.initializer());
        else out.append("null");
        out.append(";\n");
    }

   private void emitPrint(Stmt.Print p) {
    emitIndent();
    out.append("loxPrint(");
    
    // WICHTIG: Den aktuellen Scope für getVar verwenden
    if (p.expr() instanceof Expr.Variable v) {
        String varName = v.name().lexem();
         String scope = (currentFunction != null) ? currentFunctionScope : currentScope;
        out.append("getVar(").append(scope).append(", \"").append(varName).append("\")");
    } else {
        emitExpr(p.expr());
    }
    
    out.append(");\n");
}
    private void emitStmtBlock(List<Stmt> statements) {
        emitIndent(); out.append("{\n"); indent++;
        emitBlockScope(statements);
       
        indent--; emitIndent(); out.append("}\n");
    }
private void emitBlockScope(List<Stmt> statements) {
    // EIN Scope für den ganzen Block
    String blockScope = "__scope" + scopeCounter++;
    emitIndent();
    out.append("let ").append(blockScope)
       .append(" = Object.create(").append(currentScope).append(");\n");
    out.append(blockScope).append(".__parent__ = ").append(currentScope).append(";\n");

    // Scope wechseln
    String oldScope = currentScope;
    currentScope = blockScope;
    scopes.push(new HashSet<>());

    // ALLE Statements im Block mit dem GLEICHEN Scope ausführen
    for (Stmt s : statements) {
        emitStmt(s);  // Einfach! Keine if-else Unterscheidung
    }

    // Scope wiederherstellen
    scopes.pop();
    currentScope = oldScope;
}
  private void emitIf(Stmt.If i) {
        emitIndent(); 
            out.append("if (loxIsTruthy(");
            emitExpr(i.condition());
            out.append(")) ");
            emitStmt(i.thenBranch());

        i.elseBranch().ifPresent(elseBranch -> { 
            emitIndent(); out.append("else ");
            emitStmt(elseBranch);
        });
    }

    private void emitWhile(Stmt.While w) {
        emitIndent(); 
        out.append("while (loxIsTruthy(");
        emitExpr(w.condition());
        out.append(")) ");
        emitStmt(w.body());
    }
    private void emitFunction(Stmt.Function f, boolean isMethod) {
        String funcName = f.name().lexem();
        if (isMethod && funcName.equals("init")) funcName = "constructor";
            
        String previousFunction = currentFunction;
        String previousFunctionScope = currentFunctionScope; 
       
        if (isMethod){emitMethodProlog(funcName, f.params()); 

        }else{
            emitFunctionProlog(funcName, f.params());
        }
        currentFunction = funcName;
        scopes.peek().add(funcName);
        emitFunctionBody(f);
        currentFunction = previousFunction;
        currentFunctionScope = previousFunctionScope;                    
    }

    private void emitFunctionProlog(String funcName, List<Token> params) {
        emitIndent();
        String containerScope = (currentFunction != null) ? currentFunctionScope : currentScope;
        out.append(containerScope).append(".").append(funcName).append(" = function(");
        emitParams(params);
        out.append(") {\n");
         emitFunctionScope(funcName, containerScope, params);
         
    }

    private void emitFunctionBody(Stmt.Function f) {
        currentFunction = f.name().lexem();
        scopes.push(new HashSet<>());
        f.params().forEach(p -> scopes.peek().add(p.lexem()));
        f.body().forEach(this::emitStmt);
         scopes.pop();
         indent--;
        emitIndent();
        out.append("};\n");
    }
    
    private void emitMethodProlog(String funcName, List<Token> params) {
        emitIndent();
        currentFunction = funcName;
        out.append(funcName).append("("); 
        emitParams(params);
        out.append(") {\n");
        indent++;
         emitFunctionScope(funcName, currentScope, params); 
        
    }
    private void emitFunctionScope(String funcName , String containerScope, List<Token> params) {
         indent++;
         emitIndent();
         String functionScope = "__scope_" + funcName + "_" + scopeCounter++;
         out.append("let ").append(functionScope).append(" = Object.create(").append(containerScope).append(");\n");
         out.append(functionScope).append(".__parent__ = ").append(containerScope).append(";\n");
    
        for (Token param : params) {
            emitIndent();
            out.append(functionScope).append(".").append(param.lexem())
           .append(" = ").append(param.lexem()).append(";\n");
        }
         currentFunctionScope = functionScope;
    }
    private void emitClass(Stmt.Class c) {
        String prevClass = currentClass; currentClass = c.name().lexem(); classes.add(currentClass); scopes.peek().add(currentClass);
        emitIndent(); out.append(currentScope).append(".").append(currentClass).append(" = class ").append(currentClass);
        if (c.superClass() != null) { out.append(" extends "); emitExpr(c.superClass()); }
        out.append(" {\n"); indent++;
        for (Stmt.Function m : c.methods()) {
           emitFunction(m, true);
        }
        indent--; emitIndent(); out.append("};\n"); currentClass = prevClass;
    }

    private void emitReturn(Stmt.Return r) { 
        emitIndent(); out.append("return");
         if (r.value() != null) { 
            out.append(" ");
             emitExpr(r.value());
             } 
        
             out.append(";\n");
             }

    private void emitExpr(Expr expr) {
        switch (expr) {
            case Expr.Literal l -> emitLiteralExpr(l);
            case Expr.Variable v -> emitVariableExpr(v);
            case Expr.Assign a -> emitAssignExpr(a);
            case Expr.Binary b -> emitBinaryExpr(b);
            case Expr.Grouping g -> { out.append("("); emitExpr(g.expression()); out.append(")"); }
            case Expr.Unary u -> emitUnaryExpr(u);
            case Expr.Call c -> emitCallExpr(c);
            case Expr.Logical l -> emitLogicalOperator(l);
            case Expr.This t -> out.append("this");
            case Expr.Super s -> out.append("super");
            case Expr.Get g -> emitGetExpr(g);
            case Expr.Set s -> emitSetExpr(s);
            default -> throw new IllegalStateException("Unhandled expression: " + expr);
        }
    }

    // --- Helpers für Expressions ---
    private void emitLiteralExpr(Expr.Literal l) {
        Object v = l.value();
        if (v == null) out.append("null");
        else if (v instanceof String s) out.append("\"").append(escapeString(s)).append("\"");
        else if (v instanceof Double d) out.append(d == Math.rint(d) && !Double.isInfinite(d) ? String.format("%.0f", d) : d);
        else if (v instanceof Boolean b) out.append(b);
        else out.append(v);
    }

    private void emitVariableExpr(Expr.Variable v) {
        String varName = v.name().lexem();
        String scope = (currentFunction != null) ? currentFunctionScope : currentScope;
        out.append("getVar(").append(scope).append(", \"").append(varName).append("\")");
        
    }

    private void emitAssignExpr(Expr.Assign a) {
        String varName = a.name().lexem();
         String scope = (currentFunction != null) ? currentFunctionScope : currentScope;
            // Zuweisung über Scope-Kette
            out.append("setVar(").append(scope).append(", \"").append(varName).append("\", ");
            emitExpr(a.value());
            out.append(")");
        
       
    }

    private void emitBinaryExpr(Expr.Binary b) {
        String op = b.operator().lexem();
        if (op.equals("+")) { out.append("loxAdd("); emitExpr(b.left()); out.append(", "); emitExpr(b.right()); out.append(")"); }
        else if (op.equals("==")) { out.append("loxEqual("); emitExpr(b.left()); out.append(", "); emitExpr(b.right()); out.append(")"); }
        else if (op.equals("!=")) { out.append("!loxEqual("); emitExpr(b.left()); out.append(", "); emitExpr(b.right()); out.append(")"); }
        else { out.append("("); emitExpr(b.left()); out.append(" ").append(op).append(" "); emitExpr(b.right()); out.append(")"); }
    }

    private void emitUnaryExpr(Expr.Unary u) {
        String op = u.operator().lexem();
        if (op.equals("!")) { out.append("!loxIsTruthy("); emitExpr(u.right()); out.append(")"); } else { out.append(op); emitExpr(u.right()); }
    }

    private void emitCallExpr(Expr.Call c) {
        if (isSuperConstructorCall(c)) { out.append("super("); emitCommaSeparated(c.arguments()); out.append(")"); return; }
        boolean isCtor = c.callee() instanceof Expr.Variable v && classes.contains(v.name().lexem());
        if (isCtor) { out.append("new ("); emitExpr(c.callee()); out.append(")("); emitCommaSeparated(c.arguments()); out.append(")"); return; }
        if (c.callee() instanceof Expr.Super s) {
          out.append("super.").append(s.method().lexem()).append("("); emitCommaSeparated(c.arguments()); out.append(")");
            return;
        }
        emitExpr(c.callee()); out.append("("); emitCommaSeparated(c.arguments()); out.append(")");
    }

    private void emitLogicalOperator(Expr.Logical l) {
        String op = l.operator().lexem();
        if (op.equals("or")) { out.append("loxOr("); emitExpr(l.left()); out.append(", () => "); emitExpr(l.right()); out.append(")"); }
        else if (op.equals("and")) { out.append("loxAnd("); emitExpr(l.left()); out.append(", () => "); emitExpr(l.right()); out.append(")"); }
        else { out.append("("); emitExpr(l.left()); out.append(" || "); emitExpr(l.right()); out.append(")"); }
    }

    private void emitGetExpr(Expr.Get g) {
        if (g.object() instanceof Expr.This ) { emitExpr(g.object()); out.append(".").append(g.name().lexem()); }
        else if (g.object() instanceof Expr.Super) { out.append("super.").append(g.name().lexem()).append(".bind(this)"); }
        else { out.append("bindMethod("); emitExpr(g.object()); out.append(", \"").append(g.name().lexem()).append("\")"); }
    }

    private void emitSetExpr(Expr.Set s) {
        if (s.object() instanceof Expr.This || s.object() instanceof Expr.Super) { emitExpr(s.object()); out.append(".").append(s.name().lexem()).append(" = "); emitExpr(s.value()); }
        else { out.append("setVar("); emitExpr(s.object()); out.append(", \"").append(s.name().lexem()).append("\", "); emitExpr(s.value()); out.append(")"); }
    }
    private void emitLoxRuntimeHelpers() {
        out.append("\nconst loxIsTruthy = (v)=>!(v===false||v===null);\n");

        out.append("function loxAdd(a,b){if(typeof a==='number'&&typeof b==='number')return a+b;if(typeof a==='string'&&typeof b==='string')return a+b;throw new Error('Operands must be two numbers or strings.');}\n");

        out.append("function loxEqual(a,b){if(a===null&&b===null)return true;if(a===null||b===null)return false;if(typeof a==='number'&&typeof b==='number')return a===b;if(typeof a==='string'&&typeof b==='string')return a===b;if(typeof a==='boolean'&&typeof b==='boolean')return a===b;return false;}\n");

        out.append("function loxOr(a,b){return loxIsTruthy(a)?a:b();}\n");

        out.append("function loxAnd(a,b){return loxIsTruthy(a)?b():a;}\n");

        out.append("function loxPrint(v){if(v===null)console.log('nil');else console.log(String(v));return null;}\n");

        out.append("function getVar(scope,name){if(name in scope)return scope[name];if(scope.__parent__)return getVar(scope.__parent__,name);throw new Error('Variable not found: '+name);}\n");
        out.append("function setVar(scope,name,value){");
        out.append("if(Object.prototype.hasOwnProperty.call(scope,name)){");
        out.append("scope[name]=value;");
        out.append("}else if(scope.__parent__){");
        out.append("return setVar(scope.__parent__,name,value);");
        out.append("}else{");
        out.append("throw new Error('Undefined variable '+name);");
        out.append("}}");
        out.append("\n");

        out.append("function bindMethod(obj, name) {\n");
        out.append("  const value = obj[name];\n");
        out.append("  if (typeof value === 'function') return value.bind(obj);\n");
        out.append("  return value;\n");
        out.append("}\n\n");
          //out.append("function getVar(scope,name){while(scope){if(Object.prototype.hasOwnProperty.call(scope,name)){return scope[name];}scope=scope.__parent__;}throw new Error('Variable not found: '+name);}\n");
    }

    private boolean isSuperConstructorCall(Expr.Call c) { return c.callee() instanceof Expr.Super s && s.method().lexem().equals("init"); }
   
    private String escapeString(String v) { return v.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n").replace("\r","\\r").replace("\t","\\t"); }

    public static String transpile(String source) {
        try { return new JsTranspiler().transpile(ParserMain.parseProgram(source)); }
        catch(Exception e) { return "// Transpilation failed: "+e.getMessage()+"\n"; }
    }
}